name: chefarchive-web

services:
  web:
    image: ghcr.io/felipefioreti/chefarchive-web:${WEB_TAG:-latest}
    container_name: recipes-web
    restart: unless-stopped
    networks: [backend]
    environment:
      VIRTUAL_HOST: chefarchive.felipe-fioreti.tech
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: chefarchive.felipe-fioreti.tech
    expose:
      - "80"

networks:
  backend:
    external: true
    name: chefarchive_backend
